[pytest]
testpaths = tests
addopts = -v -s --strict-markers --alluredir=allure-results
markers =
    order: test order marker
    q1: Question 1 tests
    q2: Question 2 tests
    q3: Question 3 tests